"""Everything the user reads. Pure functions: (data, now) -> str.

No function here touches the clock, the filesystem or git — ``now`` is always
passed in. That is what makes the golden tests byte-stable, and byte-stability is
what lets `roadmap build` claim its output is genuinely derived.

BRIEF.md is the most important artifact in the tool. It is what an agent reads
after a compaction, after a restart, on a new machine, three weeks later. Its
section order is fixed, and three sections are EXEMPT from the token cap —
constraints, rejections, and needs-attention — because those are the three whose
loss makes an agent do damage rather than merely waste time.
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timezone

from roadmapify.journal import TRUST_FOREIGN

# ── colour ────────────────────────────────────────────────────────────────────

_NO_COLOR = bool(os.environ.get("NO_COLOR")) or not sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    return text if _NO_COLOR else f"\033[{code}m{text}\033[0m"


def bold(t: str) -> str:    return _c("1", t)
def dim(t: str) -> str:     return _c("2", t)
def red(t: str) -> str:     return _c("31", t)
def green(t: str) -> str:   return _c("32", t)
def yellow(t: str) -> str:  return _c("33", t)
def cyan(t: str) -> str:    return _c("36", t)
def magenta(t: str) -> str: return _c("35", t)


# ── time ──────────────────────────────────────────────────────────────────────

def parse_ts(ts: str) -> "datetime | None":
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError:
        return None


def ago(ts: str, now: datetime) -> str:
    """'3h', '2d 14h', '—'. Short because it appears inline everywhere."""
    then = parse_ts(ts)
    if then is None:
        return "—"
    if then.tzinfo is None:
        then = then.replace(tzinfo=timezone.utc)
    secs = max(0, int((now - then).total_seconds()))
    if secs < 90:
        return f"{secs}s"
    mins = secs // 60
    if mins < 90:
        return f"{mins}m"
    hours = mins // 60
    if hours < 48:
        return f"{hours}h"
    days, rem_h = divmod(hours, 24)
    return f"{days}d {rem_h}h" if rem_h and days < 7 else f"{days}d"


def wrap(text: str, width: int, indent: str = "") -> list[str]:
    """Greedy wrap. Deliberately not textwrap: we never want hyphen-splitting or
    whitespace normalisation inside a recorded decision."""
    words, lines, cur = text.split(), [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(indent + cur)
            cur = w
        else:
            cur = f"{cur} {w}" if cur else w
    if cur:
        lines.append(indent + cur)
    return lines or [indent]


# ── BRIEF.md ──────────────────────────────────────────────────────────────────

#: ~2,500 tokens. The cap exists because a brief nobody can afford to read is a
#: brief nobody reads; 4 chars/token is the usual English approximation.
BRIEF_CHAR_CAP = 10_000

_RECENT_DECISIONS = 8


def brief_md(plan, records: list[dict], rejections: list[dict], *, now: datetime,
             open_sessions: "list[dict] | None" = None,
             attention: "list[str] | None" = None,
             health: "str | None" = None) -> str:
    """Render BRIEF.md. Section order is fixed; three sections never truncate."""
    goal = plan.goal if plan else None
    L: list[str] = []
    superseded = {r["supersedes"] for r in records if r.get("supersedes")}

    def by(kind: str) -> list[dict]:
        return [r for r in records if r.get("kind") == kind]

    local = [r for r in records if r.get("trust") != TRUST_FOREIGN]
    foreign = [r for r in records if r.get("trust") == TRUST_FOREIGN]

    L.append("# BRIEF")
    L.append("")
    L.append("<!-- DERIVED FILE — do not edit. Regenerated by every roadmap command and")
    L.append("     every git hook. Edit roadmap.toml, or use `roadmap note`. -->")
    L.append("")

    # 1. Unclosed session, above everything except the goal itself.
    for s in open_sessions or []:
        L.append(f"> **Unclosed session {s['id']}**, opened {ago(s.get('ts', ''), now)} ago.")
        if s.get("text"):
            L.append(f"> Intent: {s['text']}")
        if s.get("branch"):
            L.append(f"> Branch: `{s['branch']}`")
        L.append("> Run `roadmap resume` before starting anything new.")
        L.append("")

    # 2. Goal and why.
    if goal and goal.label:
        L.append("## Goal")
        L.append("")
        L.append(goal.label)
        if goal.statement:
            L += ["", goal.statement]
        if goal.why:
            L += ["", f"**Why this exists:** {goal.why}"]
        if goal.success_criteria:
            L += ["", "**Done means:**"]
            L += [f"- {c}" for c in goal.success_criteria]
        L.append("")

    # 3. Constraints — never truncated.
    cons = [r for r in local if r.get("kind") == "constraint"]
    if cons:
        L.append("## Constraints (non-negotiable)")
        L.append("")
        for r in cons:
            L.append(f"- `{r['id']}` {r['text']}")
            if r.get("why"):
                L.append(f"  - {r['why']}")
        L.append("")

    # 4. The plan's shape.
    if plan and plan.phases:
        L.append("## Phases")
        L.append("")
        for p in plan.ordered_phases():
            tag = " *(provisional)*" if p.provisional else ""
            L.append(f"{p.order}. **{p.label}**{tag} — ships: {p.ships or '—'}")
        L.append("")

    # 5. Decisions — the one section the cap trims.
    decisions = [r for r in local if r.get("kind") == "decision"]
    if decisions:
        L.append("## Decisions")
        L.append("")
        shown = decisions[-_RECENT_DECISIONS:]
        if len(decisions) > len(shown):
            L.append(f"*(most recent {len(shown)} of {len(decisions)} — "
                     f"`roadmap why <id>` for the rest)*")
            L.append("")
        for r in shown:
            mark = " ~~(reversed)~~" if r["id"] in superseded else ""
            L.append(f"- `{r['id']}`{mark} {r['text']}")
            if r.get("why"):
                L.append(f"  - because {r['why']}")
            if r.get("supersedes"):
                L.append(f"  - reverses `{r['supersedes']}`")
        L.append("")

    # 6. Rejections — never truncated. This is the section that stops an agent
    #    re-proposing a dead idea, which is the single highest-value thing here.
    live = [x for x in rejections if x.get("trust") != TRUST_FOREIGN
            and x["parent"] not in superseded]
    if live:
        L.append("## Already rejected — do not re-propose")
        L.append("")
        for x in live:
            reason = f" — {x['reason']}" if x.get("reason") else ""
            L.append(f"- `{x['id']}` **{x['alt']}**{reason}")
            L.append(f"  - rejected by `{x['parent']}` {x['parent_text']}")
        L.append("")

    questions = [r for r in local if r.get("kind") == "question"]
    if questions:
        L.append("## Open questions")
        L.append("")
        L += [f"- `{r['id']}` {r['text']}" for r in questions]
        L.append("")

    risks = [r for r in local if r.get("kind") == "risk"]
    if risks:
        L.append("## Risks")
        L.append("")
        L += [f"- `{r['id']}` {r['text']}" for r in risks]
        L.append("")

    # 7. Needs attention — never truncated.
    if attention:
        L.append("## NEEDS ATTENTION")
        L.append("")
        L += [f"- {a}" for a in attention]
        L.append("")

    # 8. Foreign records, quarantined. BRIEF.md is injected into an agent's
    #    context, and a `Decision:` trailer in someone else's merged commit is
    #    untrusted input — so it is reported as an observation about what others
    #    recorded, never as an instruction, and `roadmap check` will not block on
    #    it until it is explicitly accepted.
    if foreign:
        L.append("## Recorded by others (not enforced)")
        L.append("")
        L.append("*Captured from commit trailers by other authors. Informational only —"
                 " `roadmap check` does not block on these until"
                 " `roadmap doctor --accept <id>`.*")
        L.append("")
        for r in foreign:
            L.append(f"- `{r['id']}` ({r.get('author', '?')}) {r['text']}")
        L.append("")

    L.append("---")
    L.append("")
    counts = ", ".join(f"{len(by(k))} {k}" for k in
                       ("decision", "constraint", "risk", "question") if by(k))
    L.append(f"Sources: `roadmap.toml`, `roadmap-out/journal.jsonl` "
             f"({len(records)} records{': ' + counts if counts else ''}).")
    if health:
        L.append("")
        L.append(health)
    L.append("")

    text = "\n".join(L)
    return _cap_brief(text)


def _cap_brief(text: str) -> str:
    """Trim from the Decisions section only if the brief exceeds the cap.

    Trimming anywhere else would drop a constraint or a rejection, and those are
    the two kinds of forgetting that cause an agent to actively do the wrong
    thing rather than merely re-derive something.
    """
    if len(text) <= BRIEF_CHAR_CAP:
        return text
    lines = text.split("\n")
    try:
        start = lines.index("## Decisions")
    except ValueError:
        return text
    end = next((i for i in range(start + 1, len(lines))
                if lines[i].startswith("## ")), len(lines))
    over = len(text) - BRIEF_CHAR_CAP
    kept = lines[start:end]
    dropped = 0
    while over > 0 and len(kept) > 4:
        line = kept.pop()
        over -= len(line) + 1
        dropped += 1
    if dropped:
        kept.append(f"*({dropped} older decision lines trimmed to fit the brief — "
                    f"`roadmap why` has them all)*")
    out = "\n".join(lines[:start] + kept + lines[end:])
    if len(out) > BRIEF_CHAR_CAP:
        # Decisions were the only trimmable section and trimming them was not
        # enough. Constraints, rejections and needs-attention are exempt on
        # purpose, so the brief genuinely has to be this long — but say so
        # rather than quietly shipping something twice the advertised size.
        over = len(out) - BRIEF_CHAR_CAP
        out += (f"\n> This brief is {over:,} characters over its "
                f"{BRIEF_CHAR_CAP:,} budget. Constraints and rejections are never "
                f"trimmed. If some are no longer live, retire them with "
                f"`roadmap note \"...\" --supersedes <id>`.\n")
    return out


# ── screens ───────────────────────────────────────────────────────────────────

def note_screen(rec: dict, rejections: list[dict], counts: dict) -> str:
    L = [f"{bold(rec['id'])}  {rec['kind']} recorded"]
    L.append(f"  {dim('text')}       {rec['text']}")
    if rec.get("why"):
        L.append(f"  {dim('because')}    {rec['why']}")
    for x in rejections:
        L.append(f"  {dim('rejected')}   {yellow(x['id'])}  {x['alt']}")
        if x.get("reason"):
            for ln in wrap(f"— {x['reason']}", 60, ""):
                L.append(f"             {ln}")
    if rec.get("about"):
        L.append(f"  {dim('about')}      {', '.join(rec['about'])}")
    if rec.get("supersedes"):
        L.append(f"  {dim('reverses')}   {rec['supersedes']}")
    if rec.get("review_by"):
        L.append(f"  {dim('review by')}  {rec['review_by']}")
    if rec.get("reversal_trigger"):
        L.append(f"  {dim('reverse if')} \"{rec['reversal_trigger']}\""
                 f"  [{rec.get('trigger_kind', 'manual')}]")
    L.append("")
    summary = " · ".join(f"{v} {k}" for k, v in counts.items() if v)
    L.append(dim(f"BRIEF.md updated — {summary}"))
    if rec["kind"] == "decision":
        L.append("")
        L.append(dim("tip: put this in your next commit message and the hook records it free —"))
        L.append(dim(f"     Decision: {rec['text']}"))
        if rejections:
            L.append(dim(f"     Rejected: {rejections[0]['alt']}"))
    return "\n".join(L)


def check_screen(query: str, verdict: str, hit: "dict | None", *,
                 score: float = 0.0, related=None, clause: str = "") -> str:
    """The gate's output. The exit code carries the verdict; this explains it.

    A blocked proposal ALWAYS prints the full reason, the recording date and the
    supersession escape hatch. An unexplained block is what teaches an agent to
    stop asking, and an agent that stops asking is worse off than one that never
    had a gate.
    """
    if verdict == "CLEAR":
        L = [green("CLEAR") + " — nothing recorded rules this out."]
        if related:
            L.append("")
            L.append(dim("  related, worth reading before you commit to it:"))
            for item, sc in related:
                label = item.get("alt") or item.get("text", "")
                kind = "rejected" if "alt" in item else item.get("kind", "note")
                L.append(f"    {yellow(item['id'])}  {dim(kind)}  {label}")
                reason = item.get("reason") or item.get("why") or ""
                if reason:
                    for ln in wrap(reason, 58):
                        L.append(f"              {dim(ln)}")
        return "\n".join(L)

    if verdict == "VIOLATES_CONSTRAINT":
        L = [red("VIOLATES CONSTRAINT") + dim(f"   match {score:.2f}")]
        L.append(f"  {yellow(hit['id'])}  {hit['text']}")
        if clause and clause.strip() != hit["text"].strip():
            L.append(f"          {dim('matched clause')}  \"{clause}\"")
        if hit.get("why"):
            for ln in wrap(hit["why"], 62):
                L.append(f"          {dim(ln)}")
        L.append("")
        L.append("  If the constraint has changed, record that — do not just proceed:")
        L.append(f'    roadmap note "lifting {hit["id"]}: <why>" --supersedes {hit["id"]}')
        return "\n".join(L)

    L = [red("REJECTED") + " — this project already ruled this out."
         + dim(f"   match {score:.2f}"), ""]
    L.append(f"  {yellow(hit['id'])}  \"{hit['alt']}\"")
    L.append(f"    {dim('rejected by')}  {hit['parent']}  {hit['parent_text']}")
    if hit.get("reason"):
        for i, ln in enumerate(wrap(hit["reason"], 58)):
            head = "because" if i == 0 else "       "
            L.append(f"    {dim(head)}      {ln}")
    L.append(f"    {dim('recorded')}     {hit.get('ts', '?')[:10]}")
    L.append("")
    L.append("  If you still think this is right, do not just do it —")
    L.append(f'    roadmap note "reversing {hit["parent"]}: <why>" '
             f"--supersedes {hit['parent']}")
    return "\n".join(L)


def why_screen(target: str, matches: list[dict], rejections: list[dict],
               superseded: set, *, reversed_by: "dict | None" = None) -> str:
    if not matches:
        return (f"{bold(target)}\n  nothing recorded about this.\n\n"
                f"  {dim('roadmap note')} records one.")
    L = [bold(target), ""]
    L.append("because")
    for r in matches:
        state = magenta("SUPERSEDED") if r["id"] in superseded else green("ACTIVE")
        L.append(f"  {yellow(r['id'])}  {r['text']}   {state}")
        killer = (reversed_by or {}).get(r["id"])
        if killer:
            L.append(f"          {magenta('reversed by')} {killer}"
                     f" — that decision is the one in force")
        if r.get("why"):
            for ln in wrap(r["why"], 62):
                L.append(f"          {dim(ln)}")
        for x in rejections:
            if x["parent"] != r["id"]:
                continue
            reason = f" — {x['reason']}" if x.get("reason") else ""
            L.append(f"          {dim('rejected')}  {x['alt']}{reason}")
        if r.get("supersedes"):
            L.append(f"          {dim('reverses')}  {r['supersedes']}")
        if r.get("review_by"):
            L.append(f"          {dim('review by')} {r['review_by']}")
        if r.get("reversal_trigger"):
            L.append(f"          {dim('reverse if')} \"{r['reversal_trigger']}\"")
    return "\n".join(L)


def resume_screen(session: "dict | None", new_id: "str | None", *, now: datetime,
                  dirty: "list[str] | None" = None) -> str:
    if session is None:
        return green("No unclosed session.") + "\n" + dim(
            "  Nothing was interrupted — or nothing was ever recorded.")
    L = [yellow("! UNCLOSED SESSION") + f"  {bold(session['id'])}"
         f"   opened {ago(session.get('ts', ''), now)} ago"]
    if session.get("text"):
        L.append(f"  {dim('intent')}   {session['text']}")
    if session.get("branch"):
        L.append(f"  {dim('branch')}   {session['branch']}")
    if dirty:
        shown = ", ".join(dirty[:6]) + (f" (+{len(dirty) - 6} more)" if len(dirty) > 6 else "")
        L.append(f"  {dim('dirty')}    {shown}")
    if new_id:
        L.append("")
        L.append(f"resumed as {bold(new_id)} (resumed_from {session['id']})")
    return "\n".join(L)


# ── the plan screens ──────────────────────────────────────────────────────────

SCREEN_WIDTH = 78

#: Status words in PLAIN TEXT. `_NO_COLOR` is true for every pipe, every agent
#: and every test in this suite, so "provisional tasks are dimmed" survives only
#: if the word carries the meaning and `dim()` is decoration on top of it.
STATUS_WORDS = {
    "blocked": "blocked", "ready": "ready", "active": "active",
    "done_claimed": "done*", "done": "done",
}

_STATUS_COLOUR = {"ready": green, "active": cyan, "done": green,
                  "done_claimed": yellow, "blocked": dim}


def _status_word(st, *, provisional: bool = False) -> str:
    if provisional:
        return dim("prov")
    word = STATUS_WORDS.get(st, st)
    return _STATUS_COLOUR.get(st, dim)(word)


def _no_evidence_line(snapshot) -> str:
    """The line that stops a zeroed screen being a lie by omission.

    P-3's `ships` is "roadmap next prints agreement and coverage on line 2", so
    this slot is reserved: P-3 overwrites it in place rather than restructuring
    the screen.
    """
    if snapshot.evidence_count:
        return dim(f"{snapshot.evidence_count} evidence records observed")
    return dim("no evidence recorded — nothing can read as done yet "
               "(`roadmap sync`, P-3)")


def next_screen(plan, snapshot, *, now: datetime, phase: "str | None" = None) -> str:
    L = [bold(plan.goal.label), _no_evidence_line(snapshot), ""]
    pid = phase or snapshot.active_phase
    ph = plan.phase(pid) if pid else None
    if ph is None:
        L.append(dim("every phase is complete."))
        return "\n".join(L)

    ps = snapshot.phase(ph.id)
    order = [p.id for p in plan.ordered_phases()]
    tag = dim("provisional") if ph.provisional else green("active")
    L.append(f"phase {order.index(ph.id) + 1} of {len(order)}   "
             f"{bold(ph.label):<44} {cyan(ph.id)}  {tag}")
    for label, value in (("ships", ph.ships), ("gate", ph.exit_criteria),
                         ("demo", ph.demo)):
        if not value:
            continue
        for i, line in enumerate(wrap(value, 58)):
            head = dim(f"{label:<9}") if i == 0 else " " * 9
            L.append(f"  {head}  {line}")
    if ps:
        L.append(f"  {dim('tasks')}      {ps.done} done · "
                 f"{len([t for t in snapshot.tasks if t.status == 'ready' and not t.provisional])} ready · "
                 f"{ps.total - ps.done} not done   "
                 f"({ps.total} load-bearing, {ps.provisional} provisional)")

    ready = [snapshot.task(t) for t in snapshot.ready]
    L += ["", bold("ready now")] if ready else ["", dim("nothing is ready")]
    for ts in ready[:6]:
        task = plan.task(ts.id)
        L.append(f"  {cyan(ts.id)}  {task.label:<48} {dim(f'frees {ts.unblocks}')}")

    blocked = [t for t in snapshot.tasks
               if t.status == "blocked" and not t.provisional
               and plan.task(t.id).phase == ph.id]
    if blocked:
        L += ["", dim(f"blocked in {ph.id}")]
        for ts in blocked[:8]:
            L.append(f"  {ts.id}  {plan.task(ts.id).label:<40} "
                     f"{dim('waiting on ' + ', '.join(ts.blocked_by))}")

    path = snapshot.remaining_path or snapshot.critical_path
    if path:
        L += ["", f"{bold('critical path')}   {len(path)} tasks"]
        L.append("  " + " → ".join(path))
        tail = plan.task(path[-1])
        if tail:
            L.append(dim(f"  ends at {tail.id}  {tail.label}   ({tail.phase})"))
    if snapshot.needs_expand:
        L += ["", yellow(f"{ph.id} has no load-bearing work left — "
                         f"`roadmap expand {ph.id}` promotes its tasks.")]
    return "\n".join(line.rstrip() for line in L)


def tree_screen(plan, snapshot, *, now: datetime, only_phase: "str | None" = None,
                hide_provisional: bool = False, show_deps: bool = False) -> str:
    load_bearing = [t for t in plan.tasks if not t.provisional]
    L = [bold(plan.goal.label),
         dim(f"{len(plan.phases)} phases · {len(plan.tasks)} tasks · "
             f"{len(load_bearing)} load-bearing · "
             f"{len(plan.tasks) - len(load_bearing)} provisional · "
             + ("no evidence recorded" if not snapshot.evidence_count
                else f"{snapshot.evidence_count} evidence records"))]
    for ph in plan.ordered_phases():
        if only_phase and ph.id != only_phase:
            continue
        if hide_provisional and ph.provisional:
            continue
        ps = snapshot.phase(ph.id)
        tag = (dim("provisional") if ph.provisional
               else (green("active") if ph.id == snapshot.active_phase else ""))
        L += ["", f"{cyan(ph.id)}  {bold(ph.label):<48} {tag}".rstrip()]
        if ph.provisional:
            L.append(dim(f"     not load-bearing until `roadmap expand {ph.id}`"))
        elif ps:
            L.append(dim(f"     {ps.done} of {ps.total} done"))
        for line in wrap(f"ships {ph.ships}", 66):
            L.append(dim(f"     {line}"))
        for t in sorted(plan.tasks_of(ph.id), key=lambda t: t.id):
            if hide_provisional and t.provisional:
                continue
            ts = snapshot.task(t.id)
            state = _status_word(ts.status if ts else "blocked", provisional=t.provisional)
            label = t.label if len(t.label) <= 48 else t.label[:47] + "…"
            row = f"  {t.id}  {label:<48} {state}"
            if show_deps and t.depends_on:
                row += dim(f"  ← {' '.join(t.depends_on)}")
            L.append(row)
    L += ["", dim(f"{len(load_bearing)} of {len(plan.tasks)} tasks are load-bearing. "
                  "The whole path exists; only the near part is load-bearing.")]
    return "\n".join(line.rstrip() for line in L)


def expand_screen(plan, ph, promoted: "tuple[str, ...]", *, wrote: bool,
                  brief: bool, load_bearing: int, was: int,
                  warnings: "tuple[str, ...]" = ()) -> str:
    L = [f"{cyan(ph.id)}  {bold(ph.label):<40} "
         f"{green('now load-bearing') if wrote else dim('unchanged')}"]
    for label, value in (("ships", ph.ships), ("gate", ph.exit_criteria)):
        if not value:
            continue
        for i, line in enumerate(wrap(value, 62)):
            head = dim(f"{label:<9}") if i == 0 else " " * 9
            L.append(f"  {head}  {line}")
    if promoted:
        L += ["", f"  {dim('promoted')}   {len(promoted)} tasks"]
        for tid in promoted:
            L.append(f"    {tid}  {plan.task(tid).label}")
    else:
        L += ["", dim("  nothing to promote — it was already load-bearing.")]
    if wrote:
        L += ["", f"  {dim('roadmap.toml')}   rewritten (byte-stable round trip verified)"]
        if brief:
            L.append(f"  {dim('BRIEF.md')}       re-derived")
    L += ["", f"{bold('load-bearing set')}   {load_bearing} tasks   (was {was})"]
    for w in warnings:
        L.append(yellow(f"!  {w}"))
    L += ["", dim("Nothing was added, removed or reordered, and no status was written."),
          dim("Offline `expand` only clears the provisional flag — it cannot invent"),
          dim("task detail. `roadmap expand <P-n> --llm` (P-9) refines these labels"),
          dim("inside this same fixed skeleton.")]
    return "\n".join(line.rstrip() for line in L)


def plan_errors_screen(errors: "list[str]", cycles: "list[list[str]]") -> str:
    L = []
    if cycles:
        L.append(red("the plan has a dependency cycle. There is no 'next task' in it."))
        for cyc in cycles:
            L.append("")
            L.append("  " + " → ".join(cyc))
        L += ["", dim("  break one edge in roadmap.toml, then run this again.")]
    for e in errors:
        L.append(red(f"  {e}"))
    return "\n".join(L)


def rewrite_refusal_screen(lost: "list[str]", command: str) -> str:
    """`expand` refuses rather than silently dropping a hand edit.

    roadmap.toml is the one tracked source file this tool rewrites, and its own
    header tells you to hand-edit it. `emit_plan` reproduces a fixed set of
    comments and nothing else, so a reviewer's note is data loss with no undo
    outside git.
    """
    L = [red("refusing to rewrite roadmap.toml") +
         " — it carries hand edits this version",
         "      cannot reproduce byte for byte.", ""]
    L.append(f"      {len(lost)} line(s) would be lost:")
    for line in lost[:8]:
        L.append(dim(f"        {line}"))
    if len(lost) > 8:
        L.append(dim(f"        … and {len(lost) - 8} more"))
    L += ["", dim(f"      `{command} --dry-run`  shows the change and writes nothing"),
          dim(f"      `{command} --force`    writes anyway, dropping the lines above")]
    return "\n".join(L)
